{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "zookeeper.fullname" . }}-metrics
  namespace: {{ .Release.Namespace }}
  labels: {{- include "zookeeper.labels" . | nindent 4 }}
    app.kubernetes.io/component: zookeeper
    {{- if .Values.commonLabels }}
    {{- include "zookeeper.tplvalue" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "zookeeper.tplvalue" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  ports:
    - name: tcp-metrics
      port: {{ .Values.metrics.port }}
      targetPort: metrics
  selector: {{- include "zookeeper.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: zookeeper
{{- end }}
